`timescale 1ns / 1ps

module vga_scanout #(
    parameter integer FRAME_WIDTH  = 320,
    parameter integer FRAME_HEIGHT = 240,
    parameter integer VGA_WIDTH    = 640,
    parameter integer VGA_HEIGHT   = 480,
    parameter integer VGA_X_WIDTH  = 10,
    parameter integer VGA_Y_WIDTH  = 10,
    parameter integer COLOR_WIDTH  = 12,
    parameter integer FRAMEBUFFER_ADDR_WIDTH =
        $clog2(FRAME_WIDTH * FRAME_HEIGHT)
)(
    input wire clk,
    input wire reset,

    // Signals generated by the VGA timing controller.
    input wire [VGA_X_WIDTH-1:0] vga_x,
    input wire [VGA_Y_WIDTH-1:0] vga_y,
    input wire                   timing_active_video,
    input wire                   timing_hsync,
    input wire                   timing_vsync,

    // Connection to rasterizer_top's framebuffer read port.
    output wire [FRAMEBUFFER_ADDR_WIDTH-1:0]
                                            framebuffer_read_address,
    input  wire [COLOR_WIDTH-1:0]            framebuffer_read_color,

    // Basys 3 VGA outputs.
    output wire [3:0] vga_red,
    output wire [3:0] vga_green,
    output wire [3:0] vga_blue,
    output wire       vga_hsync,
    output wire       vga_vsync
);

    wire [COLOR_WIDTH-1:0] aligned_display_color;
    wire aligned_active_video;
    wire aligned_hsync;
    wire aligned_vsync;

    framebuffer_reader #(
        .FRAME_WIDTH  (FRAME_WIDTH),
        .FRAME_HEIGHT (FRAME_HEIGHT),
        .COLOR_WIDTH  (COLOR_WIDTH),
        .VGA_WIDTH    (VGA_WIDTH),
        .VGA_HEIGHT   (VGA_HEIGHT),
        .VGA_X_WIDTH  (VGA_X_WIDTH),
        .VGA_Y_WIDTH  (VGA_Y_WIDTH),
        .ADDRESS_WIDTH(FRAMEBUFFER_ADDR_WIDTH)
    ) framebuffer_reader_instance (
        .clk                       (clk),
        .reset                     (reset),
        .vga_x                     (vga_x),
        .vga_y                     (vga_y),
        .vga_active_video          (timing_active_video),
        .vga_hsync                 (timing_hsync),
        .vga_vsync                 (timing_vsync),
        .framebuffer_read_address  (framebuffer_read_address),
        .framebuffer_read_color    (framebuffer_read_color),
        .display_color             (aligned_display_color),
        .display_active_video      (aligned_active_video),
        .display_hsync             (aligned_hsync),
        .display_vsync             (aligned_vsync)
    );



    assign vga_red = aligned_active_video
                   ? aligned_display_color[11:8]
                   : 4'b0000;

    assign vga_green = aligned_active_video
                     ? aligned_display_color[7:4]
                     : 4'b0000;

    assign vga_blue = aligned_active_video
                    ? aligned_display_color[3:0]
                    : 4'b0000;

    assign vga_hsync = aligned_hsync;
    assign vga_vsync = aligned_vsync;

endmodule
